// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addAnalyticsPageStatToTarget = `-- name: AddAnalyticsPageStatToTarget :one
INSERT INTO
    analytics_page_stats_on_target (
        id,
        synced_at,
        stat_id,
        target_id,
        target_record_id
    )
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (stat_id, target_id) DO
UPDATE
SET
    synced_at = $2,
    target_record_id = $5
RETURNING
    id, synced_at, stat_id, target_id, target_record_id
`

type AddAnalyticsPageStatToTargetParams struct {
	ID             uuid.UUID
	SyncedAt       time.Time
	StatID         uuid.NullUUID
	TargetID       uuid.UUID
	TargetRecordID string
}

func (q *Queries) AddAnalyticsPageStatToTarget(ctx context.Context, arg AddAnalyticsPageStatToTargetParams) (AnalyticsPageStatsOnTarget, error) {
	row := q.db.QueryRowContext(ctx, addAnalyticsPageStatToTarget,
		arg.ID,
		arg.SyncedAt,
		arg.StatID,
		arg.TargetID,
		arg.TargetRecordID,
	)
	var i AnalyticsPageStatsOnTarget
	err := row.Scan(
		&i.ID,
		&i.SyncedAt,
		&i.StatID,
		&i.TargetID,
		&i.TargetRecordID,
	)
	return i, err
}

const addAnalyticsSiteStatToTarget = `-- name: AddAnalyticsSiteStatToTarget :one
INSERT INTO
    analytics_site_stats_on_target (
        id,
        synced_at,
        stat_id,
        target_id,
        target_record_id
    )
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (stat_id, target_id) DO
UPDATE
SET
    synced_at = $2,
    target_record_id = $5
RETURNING
    id, synced_at, stat_id, target_id, target_record_id
`

type AddAnalyticsSiteStatToTargetParams struct {
	ID             uuid.UUID
	SyncedAt       time.Time
	StatID         uuid.NullUUID
	TargetID       uuid.UUID
	TargetRecordID string
}

func (q *Queries) AddAnalyticsSiteStatToTarget(ctx context.Context, arg AddAnalyticsSiteStatToTargetParams) (AnalyticsSiteStatsOnTarget, error) {
	row := q.db.QueryRowContext(ctx, addAnalyticsSiteStatToTarget,
		arg.ID,
		arg.SyncedAt,
		arg.StatID,
		arg.TargetID,
		arg.TargetRecordID,
	)
	var i AnalyticsSiteStatsOnTarget
	err := row.Scan(
		&i.ID,
		&i.SyncedAt,
		&i.StatID,
		&i.TargetID,
		&i.TargetRecordID,
	)
	return i, err
}

const checkCountOfAnalyticsPageStatsForUser = `-- name: CheckCountOfAnalyticsPageStatsForUser :one
SELECT COUNT(*)
FROM
    analytics_page_stats s
    join sources src on s.source_id = src.id
where
    src.user_id = $1
`

func (q *Queries) CheckCountOfAnalyticsPageStatsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCountOfAnalyticsPageStatsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkCountOfAnalyticsSiteStatsForUser = `-- name: CheckCountOfAnalyticsSiteStatsForUser :one
SELECT COUNT(*)
FROM
    analytics_site_stats s
    join sources src on s.source_id = src.id
where
    src.user_id = $1
`

func (q *Queries) CheckCountOfAnalyticsSiteStatsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCountOfAnalyticsSiteStatsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAnalyticsSiteStatsBySource = `-- name: CountAnalyticsSiteStatsBySource :one
SELECT COUNT(*) FROM analytics_site_stats WHERE source_id = $1
`

func (q *Queries) CountAnalyticsSiteStatsBySource(ctx context.Context, sourceID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAnalyticsSiteStatsBySource, sourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnalyticsPageStat = `-- name: CreateAnalyticsPageStat :one
INSERT INTO
    analytics_page_stats (
        id,
        date,
        url_path,
        views,
        source_id
    )
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (source_id, date, url_path) DO
UPDATE
SET
    views = $4
RETURNING
    id, date, url_path, views, source_id
`

type CreateAnalyticsPageStatParams struct {
	ID       uuid.UUID
	Date     time.Time
	UrlPath  string
	Views    int
	SourceID uuid.UUID
}

func (q *Queries) CreateAnalyticsPageStat(ctx context.Context, arg CreateAnalyticsPageStatParams) (AnalyticsPageStat, error) {
	row := q.db.QueryRowContext(ctx, createAnalyticsPageStat,
		arg.ID,
		arg.Date,
		arg.UrlPath,
		arg.Views,
		arg.SourceID,
	)
	var i AnalyticsPageStat
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.UrlPath,
		&i.Views,
		&i.SourceID,
	)
	return i, err
}

const createAnalyticsSiteStat = `-- name: CreateAnalyticsSiteStat :one
INSERT INTO
    analytics_site_stats (
        id,
        date,
        visitors,
        avg_session_duration,
        source_id
    )
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (source_id, date) DO
UPDATE
SET
    visitors = EXCLUDED.visitors,
    avg_session_duration = EXCLUDED.avg_session_duration
RETURNING
    id, date, visitors, avg_session_duration, source_id
`

type CreateAnalyticsSiteStatParams struct {
	ID                 uuid.UUID
	Date               time.Time
	Visitors           int
	AvgSessionDuration float64
	SourceID           uuid.UUID
}

func (q *Queries) CreateAnalyticsSiteStat(ctx context.Context, arg CreateAnalyticsSiteStatParams) (AnalyticsSiteStat, error) {
	row := q.db.QueryRowContext(ctx, createAnalyticsSiteStat,
		arg.ID,
		arg.Date,
		arg.Visitors,
		arg.AvgSessionDuration,
		arg.SourceID,
	)
	var i AnalyticsSiteStat
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Visitors,
		&i.AvgSessionDuration,
		&i.SourceID,
	)
	return i, err
}

const deleteAnalyticsPageStat = `-- name: DeleteAnalyticsPageStat :exec
DELETE FROM analytics_page_stats WHERE id = $1
`

func (q *Queries) DeleteAnalyticsPageStat(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAnalyticsPageStat, id)
	return err
}

const deleteAnalyticsPageStatsByPathAndSource = `-- name: DeleteAnalyticsPageStatsByPathAndSource :exec
DELETE FROM analytics_page_stats
WHERE
    source_id = $1
    AND url_path = $2
`

type DeleteAnalyticsPageStatsByPathAndSourceParams struct {
	SourceID uuid.UUID
	UrlPath  string
}

func (q *Queries) DeleteAnalyticsPageStatsByPathAndSource(ctx context.Context, arg DeleteAnalyticsPageStatsByPathAndSourceParams) error {
	_, err := q.db.ExecContext(ctx, deleteAnalyticsPageStatsByPathAndSource, arg.SourceID, arg.UrlPath)
	return err
}

const getAllAnalyticsPageStatsForUser = `-- name: GetAllAnalyticsPageStatsForUser :many
SELECT
    s.id, s.date, s.url_path, s.views, s.source_id,
    src.network as source_network,
    src.user_name as source_user_name
FROM
    analytics_page_stats s
    JOIN sources src ON s.source_id = src.id
WHERE
    src.user_id = $1
ORDER BY s.date DESC
`

type GetAllAnalyticsPageStatsForUserRow struct {
	ID             uuid.UUID
	Date           time.Time
	UrlPath        string
	Views          int
	SourceID       uuid.UUID
	SourceNetwork  string
	SourceUserName string
}

func (q *Queries) GetAllAnalyticsPageStatsForUser(ctx context.Context, userID uuid.UUID) ([]GetAllAnalyticsPageStatsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAnalyticsPageStatsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAnalyticsPageStatsForUserRow
	for rows.Next() {
		var i GetAllAnalyticsPageStatsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.UrlPath,
			&i.Views,
			&i.SourceID,
			&i.SourceNetwork,
			&i.SourceUserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAnalyticsSiteStatsForUser = `-- name: GetAllAnalyticsSiteStatsForUser :many
SELECT
    s.id, s.date, s.visitors, s.avg_session_duration, s.source_id,
    src.network as source_network,
    src.user_name as source_user_name
FROM
    analytics_site_stats s
    JOIN sources src ON s.source_id = src.id
WHERE
    src.user_id = $1
ORDER BY s.date DESC
`

type GetAllAnalyticsSiteStatsForUserRow struct {
	ID                 uuid.UUID
	Date               time.Time
	Visitors           int
	AvgSessionDuration float64
	SourceID           uuid.UUID
	SourceNetwork      string
	SourceUserName     string
}

func (q *Queries) GetAllAnalyticsSiteStatsForUser(ctx context.Context, userID uuid.UUID) ([]GetAllAnalyticsSiteStatsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllAnalyticsSiteStatsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAnalyticsSiteStatsForUserRow
	for rows.Next() {
		var i GetAllAnalyticsSiteStatsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Visitors,
			&i.AvgSessionDuration,
			&i.SourceID,
			&i.SourceNetwork,
			&i.SourceUserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPageStatsWithTargetInfo = `-- name: GetAllPageStatsWithTargetInfo :many
SELECT s.id, s.date, s.url_path, s.views, s.source_id, map.target_record_id
FROM
    analytics_page_stats s
    LEFT JOIN analytics_page_stats_on_target map ON s.id = map.stat_id
    AND map.target_id = $1
WHERE
    s.source_id = $2
`

type GetAllPageStatsWithTargetInfoParams struct {
	TargetID uuid.UUID
	SourceID uuid.UUID
}

type GetAllPageStatsWithTargetInfoRow struct {
	ID             uuid.UUID
	Date           time.Time
	UrlPath        string
	Views          int
	SourceID       uuid.UUID
	TargetRecordID sql.NullString
}

func (q *Queries) GetAllPageStatsWithTargetInfo(ctx context.Context, arg GetAllPageStatsWithTargetInfoParams) ([]GetAllPageStatsWithTargetInfoRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPageStatsWithTargetInfo, arg.TargetID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPageStatsWithTargetInfoRow
	for rows.Next() {
		var i GetAllPageStatsWithTargetInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.UrlPath,
			&i.Views,
			&i.SourceID,
			&i.TargetRecordID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSiteStatsWithTargetInfo = `-- name: GetAllSiteStatsWithTargetInfo :many
SELECT s.id, s.date, s.visitors, s.avg_session_duration, s.source_id, map.target_record_id
FROM
    analytics_site_stats s
    LEFT JOIN analytics_site_stats_on_target map ON s.id = map.stat_id
    AND map.target_id = $1
WHERE
    s.source_id = $2
`

type GetAllSiteStatsWithTargetInfoParams struct {
	TargetID uuid.UUID
	SourceID uuid.UUID
}

type GetAllSiteStatsWithTargetInfoRow struct {
	ID                 uuid.UUID
	Date               time.Time
	Visitors           int
	AvgSessionDuration float64
	SourceID           uuid.UUID
	TargetRecordID     sql.NullString
}

func (q *Queries) GetAllSiteStatsWithTargetInfo(ctx context.Context, arg GetAllSiteStatsWithTargetInfoParams) ([]GetAllSiteStatsWithTargetInfoRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllSiteStatsWithTargetInfo, arg.TargetID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSiteStatsWithTargetInfoRow
	for rows.Next() {
		var i GetAllSiteStatsWithTargetInfoRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Visitors,
			&i.AvgSessionDuration,
			&i.SourceID,
			&i.TargetRecordID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalyticsPageStatsBySource = `-- name: GetAnalyticsPageStatsBySource :many
SELECT id, date, url_path, views, source_id
FROM analytics_page_stats
WHERE
    source_id = $1
ORDER BY date DESC
`

func (q *Queries) GetAnalyticsPageStatsBySource(ctx context.Context, sourceID uuid.UUID) ([]AnalyticsPageStat, error) {
	rows, err := q.db.QueryContext(ctx, getAnalyticsPageStatsBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsPageStat
	for rows.Next() {
		var i AnalyticsPageStat
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.UrlPath,
			&i.Views,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalyticsSiteStatsBySource = `-- name: GetAnalyticsSiteStatsBySource :many
SELECT id, date, visitors, avg_session_duration, source_id
FROM analytics_site_stats
WHERE
    source_id = $1
ORDER BY date DESC
`

func (q *Queries) GetAnalyticsSiteStatsBySource(ctx context.Context, sourceID uuid.UUID) ([]AnalyticsSiteStat, error) {
	rows, err := q.db.QueryContext(ctx, getAnalyticsSiteStatsBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsSiteStat
	for rows.Next() {
		var i AnalyticsSiteStat
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Visitors,
			&i.AvgSessionDuration,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalyticsSiteStatsBySourceAndRange = `-- name: GetAnalyticsSiteStatsBySourceAndRange :many
SELECT id, date, visitors, avg_session_duration, source_id
FROM analytics_site_stats
WHERE
    source_id = $1
    AND date >= $2
    AND date <= $3
ORDER BY date DESC
`

type GetAnalyticsSiteStatsBySourceAndRangeParams struct {
	SourceID uuid.UUID
	Date     time.Time
	Date_2   time.Time
}

func (q *Queries) GetAnalyticsSiteStatsBySourceAndRange(ctx context.Context, arg GetAnalyticsSiteStatsBySourceAndRangeParams) ([]AnalyticsSiteStat, error) {
	rows, err := q.db.QueryContext(ctx, getAnalyticsSiteStatsBySourceAndRange, arg.SourceID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsSiteStat
	for rows.Next() {
		var i AnalyticsSiteStat
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Visitors,
			&i.AvgSessionDuration,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyEngagementStats = `-- name: GetMonthlyEngagementStats :many
WITH
    LatestStats AS (
        SELECT prh.post_id, prh.likes, prh.reposts
        FROM
            posts_reactions_history prh
            JOIN (
                SELECT post_id, MAX(synced_at) as max_sync
                FROM posts_reactions_history
                GROUP BY
                    post_id
            ) latest ON prh.post_id = latest.post_id
            AND prh.synced_at = latest.max_sync
    )
SELECT
    s.id,
    s.network,
    s.user_name,
    TO_CHAR(p.created_at, 'YYYY-MM') as year_month,
    COALESCE(SUM(ls.likes), 0)::bigint as total_likes,
    COALESCE(SUM(ls.reposts), 0)::bigint as total_reposts
FROM
    posts p
    JOIN sources s ON p.source_id = s.id
    JOIN LatestStats ls ON p.id = ls.post_id
WHERE
    s.user_id = $1
    AND p.post_type <> 'repost'
GROUP BY
    s.id,
    s.network,
    s.user_name,
    year_month
ORDER BY year_month ASC
`

type GetMonthlyEngagementStatsRow struct {
	ID           uuid.UUID
	Network      string
	UserName     string
	YearMonth    string
	TotalLikes   int
	TotalReposts int
}

func (q *Queries) GetMonthlyEngagementStats(ctx context.Context, userID uuid.UUID) ([]GetMonthlyEngagementStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlyEngagementStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyEngagementStatsRow
	for rows.Next() {
		var i GetMonthlyEngagementStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Network,
			&i.UserName,
			&i.YearMonth,
			&i.TotalLikes,
			&i.TotalReposts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyPageViews = `-- name: GetMonthlyPageViews :many
SELECT TO_CHAR(s.date, 'YYYY-MM') as year_month, COALESCE(SUM(s.views), 0)::bigint as total_views
FROM
    analytics_page_stats s
    JOIN sources src ON s.source_id = src.id
WHERE
    src.user_id = $1
GROUP BY
    year_month
ORDER BY year_month ASC
`

type GetMonthlyPageViewsRow struct {
	YearMonth  string
	TotalViews int
}

func (q *Queries) GetMonthlyPageViews(ctx context.Context, userID uuid.UUID) ([]GetMonthlyPageViewsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlyPageViews, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyPageViewsRow
	for rows.Next() {
		var i GetMonthlyPageViewsRow
		if err := rows.Scan(&i.YearMonth, &i.TotalViews); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlySiteVisitors = `-- name: GetMonthlySiteVisitors :many
SELECT
    TO_CHAR(s.date, 'YYYY-MM') as year_month,
    COALESCE(SUM(s.visitors), 0)::bigint as total_visitors
FROM
    analytics_site_stats s
    JOIN sources src ON s.source_id = src.id
WHERE
    src.user_id = $1
GROUP BY
    year_month
ORDER BY year_month ASC
`

type GetMonthlySiteVisitorsRow struct {
	YearMonth     string
	TotalVisitors int
}

func (q *Queries) GetMonthlySiteVisitors(ctx context.Context, userID uuid.UUID) ([]GetMonthlySiteVisitorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlySiteVisitors, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlySiteVisitorsRow
	for rows.Next() {
		var i GetMonthlySiteVisitorsRow
		if err := rows.Scan(&i.YearMonth, &i.TotalVisitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncedPageStatsForUpdate = `-- name: GetSyncedPageStatsForUpdate :many
SELECT s.id, s.date, s.url_path, s.views, s.source_id, map.target_record_id
FROM
    analytics_page_stats s
    JOIN analytics_page_stats_on_target map ON s.id = map.stat_id
    AND map.target_id = $1
WHERE
    s.source_id = $2
    AND s.date >= $3
`

type GetSyncedPageStatsForUpdateParams struct {
	TargetID uuid.UUID
	SourceID uuid.UUID
	Date     time.Time
}

type GetSyncedPageStatsForUpdateRow struct {
	ID             uuid.UUID
	Date           time.Time
	UrlPath        string
	Views          int
	SourceID       uuid.UUID
	TargetRecordID string
}

func (q *Queries) GetSyncedPageStatsForUpdate(ctx context.Context, arg GetSyncedPageStatsForUpdateParams) ([]GetSyncedPageStatsForUpdateRow, error) {
	rows, err := q.db.QueryContext(ctx, getSyncedPageStatsForUpdate, arg.TargetID, arg.SourceID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSyncedPageStatsForUpdateRow
	for rows.Next() {
		var i GetSyncedPageStatsForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.UrlPath,
			&i.Views,
			&i.SourceID,
			&i.TargetRecordID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncedSiteStatsForUpdate = `-- name: GetSyncedSiteStatsForUpdate :many
SELECT s.id, s.date, s.visitors, s.avg_session_duration, s.source_id, map.target_record_id
FROM
    analytics_site_stats s
    JOIN analytics_site_stats_on_target map ON s.id = map.stat_id
    AND map.target_id = $1
WHERE
    s.source_id = $2
    AND s.date >= $3
`

type GetSyncedSiteStatsForUpdateParams struct {
	TargetID uuid.UUID
	SourceID uuid.UUID
	Date     time.Time
}

type GetSyncedSiteStatsForUpdateRow struct {
	ID                 uuid.UUID
	Date               time.Time
	Visitors           int
	AvgSessionDuration float64
	SourceID           uuid.UUID
	TargetRecordID     string
}

func (q *Queries) GetSyncedSiteStatsForUpdate(ctx context.Context, arg GetSyncedSiteStatsForUpdateParams) ([]GetSyncedSiteStatsForUpdateRow, error) {
	rows, err := q.db.QueryContext(ctx, getSyncedSiteStatsForUpdate, arg.TargetID, arg.SourceID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSyncedSiteStatsForUpdateRow
	for rows.Next() {
		var i GetSyncedSiteStatsForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Visitors,
			&i.AvgSessionDuration,
			&i.SourceID,
			&i.TargetRecordID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnsyncedPageStatsForTarget = `-- name: GetUnsyncedPageStatsForTarget :many
SELECT s.id, s.date, s.url_path, s.views, s.source_id
FROM
    analytics_page_stats s
    LEFT JOIN analytics_page_stats_on_target map ON s.id = map.stat_id
    AND map.target_id = $1
WHERE
    map.id IS NULL
    AND s.source_id = $2
`

type GetUnsyncedPageStatsForTargetParams struct {
	TargetID uuid.UUID
	SourceID uuid.UUID
}

func (q *Queries) GetUnsyncedPageStatsForTarget(ctx context.Context, arg GetUnsyncedPageStatsForTargetParams) ([]AnalyticsPageStat, error) {
	rows, err := q.db.QueryContext(ctx, getUnsyncedPageStatsForTarget, arg.TargetID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsPageStat
	for rows.Next() {
		var i AnalyticsPageStat
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.UrlPath,
			&i.Views,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnsyncedSiteStatsForTarget = `-- name: GetUnsyncedSiteStatsForTarget :many
SELECT s.id, s.date, s.visitors, s.avg_session_duration, s.source_id
FROM
    analytics_site_stats s
    LEFT JOIN analytics_site_stats_on_target map ON s.id = map.stat_id
    AND map.target_id = $1
WHERE
    map.id IS NULL
    AND s.source_id = $2
`

type GetUnsyncedSiteStatsForTargetParams struct {
	TargetID uuid.UUID
	SourceID uuid.UUID
}

func (q *Queries) GetUnsyncedSiteStatsForTarget(ctx context.Context, arg GetUnsyncedSiteStatsForTargetParams) ([]AnalyticsSiteStat, error) {
	rows, err := q.db.QueryContext(ctx, getUnsyncedSiteStatsForTarget, arg.TargetID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsSiteStat
	for rows.Next() {
		var i AnalyticsSiteStat
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Visitors,
			&i.AvgSessionDuration,
			&i.SourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnalyticsPageStatPath = `-- name: UpdateAnalyticsPageStatPath :exec
UPDATE analytics_page_stats SET url_path = $2 WHERE id = $1
`

type UpdateAnalyticsPageStatPathParams struct {
	ID      uuid.UUID
	UrlPath string
}

func (q *Queries) UpdateAnalyticsPageStatPath(ctx context.Context, arg UpdateAnalyticsPageStatPathParams) error {
	_, err := q.db.ExecContext(ctx, updateAnalyticsPageStatPath, arg.ID, arg.UrlPath)
	return err
}
