// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics_sync_helpers.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteAnalyticsPageStatOnTarget = `-- name: DeleteAnalyticsPageStatOnTarget :exec
DELETE FROM analytics_page_stats_on_target WHERE id = $1
`

func (q *Queries) DeleteAnalyticsPageStatOnTarget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAnalyticsPageStatOnTarget, id)
	return err
}

const deleteAnalyticsSiteStatOnTarget = `-- name: DeleteAnalyticsSiteStatOnTarget :exec
DELETE FROM analytics_site_stats_on_target WHERE id = $1
`

func (q *Queries) DeleteAnalyticsSiteStatOnTarget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAnalyticsSiteStatOnTarget, id)
	return err
}

const getPageStatsOnTarget = `-- name: GetPageStatsOnTarget :many
SELECT id, synced_at, stat_id, target_id, target_record_id FROM analytics_page_stats_on_target WHERE target_id = $1
`

func (q *Queries) GetPageStatsOnTarget(ctx context.Context, targetID uuid.UUID) ([]AnalyticsPageStatsOnTarget, error) {
	rows, err := q.db.QueryContext(ctx, getPageStatsOnTarget, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsPageStatsOnTarget
	for rows.Next() {
		var i AnalyticsPageStatsOnTarget
		if err := rows.Scan(
			&i.ID,
			&i.SyncedAt,
			&i.StatID,
			&i.TargetID,
			&i.TargetRecordID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSiteStatsOnTarget = `-- name: GetSiteStatsOnTarget :many
SELECT id, synced_at, stat_id, target_id, target_record_id FROM analytics_site_stats_on_target WHERE target_id = $1
`

func (q *Queries) GetSiteStatsOnTarget(ctx context.Context, targetID uuid.UUID) ([]AnalyticsSiteStatsOnTarget, error) {
	rows, err := q.db.QueryContext(ctx, getSiteStatsOnTarget, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnalyticsSiteStatsOnTarget
	for rows.Next() {
		var i AnalyticsSiteStatsOnTarget
		if err := rows.Scan(
			&i.ID,
			&i.SyncedAt,
			&i.StatID,
			&i.TargetID,
			&i.TargetRecordID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
