// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_config.sql

package database

import (
	"context"
)

const getAppConfig = `-- name: GetAppConfig :one
SELECT value FROM app_config WHERE key = $1 LIMIT 1
`

func (q *Queries) GetAppConfig(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAppConfig, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setAppConfig = `-- name: SetAppConfig :exec
INSERT INTO
    app_config (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO
UPDATE
SET
    value = $2
`

type SetAppConfigParams struct {
	Key   string
	Value string
}

func (q *Queries) SetAppConfig(ctx context.Context, arg SetAppConfigParams) error {
	_, err := q.db.ExecContext(ctx, setAppConfig, arg.Key, arg.Value)
	return err
}
