// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package database

import (
	"context"
)

const getActiveSourcesCount = `-- name: GetActiveSourcesCount :one
SELECT COUNT(*) FROM sources
`

func (q *Queries) GetActiveSourcesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getActiveSourcesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveTargetsCount = `-- name: GetActiveTargetsCount :one
SELECT COUNT(*) FROM targets
`

func (q *Queries) GetActiveTargetsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getActiveTargetsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalPageViews = `-- name: GetTotalPageViews :one
SELECT COALESCE(SUM(views), 0)::BIGINT AS total_page_views
FROM analytics_page_stats
`

func (q *Queries) GetTotalPageViews(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalPageViews)
	var total_page_views int64
	err := row.Scan(&total_page_views)
	return total_page_views, err
}

const getTotalPostsCount = `-- name: GetTotalPostsCount :one
SELECT COUNT(*) FROM posts
`

func (q *Queries) GetTotalPostsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalPostsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalReactions = `-- name: GetTotalReactions :one
SELECT
    COALESCE(SUM(likes), 0)::BIGINT AS total_likes,
    COALESCE(SUM(reposts), 0)::BIGINT AS total_shares,
    COALESCE(SUM(views), 0)::BIGINT AS total_views
FROM (
        SELECT DISTINCT
            ON (post_id) likes, reposts, views
        FROM posts_reactions_history
        ORDER BY post_id, synced_at DESC
    ) AS latest_reactions
`

type GetTotalReactionsRow struct {
	TotalLikes  int64
	TotalShares int64
	TotalViews  int64
}

func (q *Queries) GetTotalReactions(ctx context.Context) (GetTotalReactionsRow, error) {
	row := q.db.QueryRowContext(ctx, getTotalReactions)
	var i GetTotalReactionsRow
	err := row.Scan(&i.TotalLikes, &i.TotalShares, &i.TotalViews)
	return i, err
}

const getTotalSiteStats = `-- name: GetTotalSiteStats :one
SELECT COALESCE(SUM(visitors), 0)::BIGINT AS total_visitors
FROM analytics_site_stats
`

func (q *Queries) GetTotalSiteStats(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalSiteStats)
	var total_visitors int64
	err := row.Scan(&total_visitors)
	return total_visitors, err
}
