// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exclusions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createExclusion = `-- name: CreateExclusion :one
INSERT INTO
    exclusions (
        id,
        created_at,
        source_id,
        network_internal_id
    )
VALUES ($1, $2, $3, $4)
RETURNING
    id, created_at, source_id, network_internal_id
`

type CreateExclusionParams struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	SourceID          uuid.UUID
	NetworkInternalID string
}

func (q *Queries) CreateExclusion(ctx context.Context, arg CreateExclusionParams) (Exclusion, error) {
	row := q.db.QueryRowContext(ctx, createExclusion,
		arg.ID,
		arg.CreatedAt,
		arg.SourceID,
		arg.NetworkInternalID,
	)
	var i Exclusion
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SourceID,
		&i.NetworkInternalID,
	)
	return i, err
}

const deleteExclusion = `-- name: DeleteExclusion :exec
DELETE FROM exclusions WHERE id = $1
`

func (q *Queries) DeleteExclusion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteExclusion, id)
	return err
}

const deletePostBySourceAndNetworkId = `-- name: DeletePostBySourceAndNetworkId :exec
DELETE FROM posts WHERE source_id = $1 AND network_internal_id = $2
`

type DeletePostBySourceAndNetworkIdParams struct {
	SourceID          uuid.UUID
	NetworkInternalID string
}

func (q *Queries) DeletePostBySourceAndNetworkId(ctx context.Context, arg DeletePostBySourceAndNetworkIdParams) error {
	_, err := q.db.ExecContext(ctx, deletePostBySourceAndNetworkId, arg.SourceID, arg.NetworkInternalID)
	return err
}

const getExclusionsForSource = `-- name: GetExclusionsForSource :many
SELECT id, created_at, source_id, network_internal_id
FROM exclusions
WHERE
    source_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetExclusionsForSource(ctx context.Context, sourceID uuid.UUID) ([]Exclusion, error) {
	rows, err := q.db.QueryContext(ctx, getExclusionsForSource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exclusion
	for rows.Next() {
		var i Exclusion
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SourceID,
			&i.NetworkInternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExclusionsForUser = `-- name: GetExclusionsForUser :many
SELECT e.id, e.created_at, e.source_id, e.network_internal_id, s.network, s.user_name
FROM exclusions e
    JOIN sources s ON e.source_id = s.id
WHERE
    s.user_id = $1
ORDER BY e.created_at DESC
`

type GetExclusionsForUserRow struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	SourceID          uuid.UUID
	NetworkInternalID string
	Network           string
	UserName          string
}

func (q *Queries) GetExclusionsForUser(ctx context.Context, userID uuid.UUID) ([]GetExclusionsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getExclusionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExclusionsForUserRow
	for rows.Next() {
		var i GetExclusionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SourceID,
			&i.NetworkInternalID,
			&i.Network,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
