// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exports.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const changeExportStatusById = `-- name: ChangeExportStatusById :one
UPDATE exports
SET
    export_status = $2,
    status_message = $3,
    download_url = $4,
    completed_at = $5
WHERE
    id = $1
RETURNING
    id, created_at, completed_at, export_status, status_message, user_id, download_url, export_method, target_id
`

type ChangeExportStatusByIdParams struct {
	ID            uuid.UUID
	ExportStatus  string
	StatusMessage sql.NullString
	DownloadUrl   sql.NullString
	CompletedAt   time.Time
}

func (q *Queries) ChangeExportStatusById(ctx context.Context, arg ChangeExportStatusByIdParams) (Export, error) {
	row := q.db.QueryRowContext(ctx, changeExportStatusById,
		arg.ID,
		arg.ExportStatus,
		arg.StatusMessage,
		arg.DownloadUrl,
		arg.CompletedAt,
	)
	var i Export
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExportStatus,
		&i.StatusMessage,
		&i.UserID,
		&i.DownloadUrl,
		&i.ExportMethod,
		&i.TargetID,
	)
	return i, err
}

const createExport = `-- name: CreateExport :one
INSERT INTO
    exports (
        id,
        created_at,
        completed_at,
        export_status,
        status_message,
        user_id,
        download_url,
        export_method,
        target_id
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9
    )
RETURNING
    id, created_at, completed_at, export_status, status_message, user_id, download_url, export_method, target_id
`

type CreateExportParams struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	CompletedAt   time.Time
	ExportStatus  string
	StatusMessage sql.NullString
	UserID        uuid.UUID
	DownloadUrl   sql.NullString
	ExportMethod  string
	TargetID      uuid.NullUUID
}

func (q *Queries) CreateExport(ctx context.Context, arg CreateExportParams) (Export, error) {
	row := q.db.QueryRowContext(ctx, createExport,
		arg.ID,
		arg.CreatedAt,
		arg.CompletedAt,
		arg.ExportStatus,
		arg.StatusMessage,
		arg.UserID,
		arg.DownloadUrl,
		arg.ExportMethod,
		arg.TargetID,
	)
	var i Export
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExportStatus,
		&i.StatusMessage,
		&i.UserID,
		&i.DownloadUrl,
		&i.ExportMethod,
		&i.TargetID,
	)
	return i, err
}

const deleteAllExportsByUserId = `-- name: DeleteAllExportsByUserId :exec
DELETE FROM exports WHERE user_id = $1
`

func (q *Queries) DeleteAllExportsByUserId(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllExportsByUserId, userID)
	return err
}

const getAllExportsByUserId = `-- name: GetAllExportsByUserId :many
SELECT id, created_at, completed_at, export_status, status_message, user_id, download_url, export_method, target_id FROM exports where user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetAllExportsByUserId(ctx context.Context, userID uuid.UUID) ([]Export, error) {
	rows, err := q.db.QueryContext(ctx, getAllExportsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Export
	for rows.Next() {
		var i Export
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ExportStatus,
			&i.StatusMessage,
			&i.UserID,
			&i.DownloadUrl,
			&i.ExportMethod,
			&i.TargetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExportById = `-- name: GetExportById :one
SELECT id, created_at, completed_at, export_status, status_message, user_id, download_url, export_method, target_id FROM exports WHERE id = $1
`

func (q *Queries) GetExportById(ctx context.Context, id uuid.UUID) (Export, error) {
	row := q.db.QueryRowContext(ctx, getExportById, id)
	var i Export
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExportStatus,
		&i.StatusMessage,
		&i.UserID,
		&i.DownloadUrl,
		&i.ExportMethod,
		&i.TargetID,
	)
	return i, err
}

const getLast20ExportsByUserId = `-- name: GetLast20ExportsByUserId :many
SELECT id, created_at, completed_at, export_status, status_message, user_id, download_url, export_method, target_id
FROM exports
where
    user_id = $1
ORDER BY created_at DESC
LIMIT 20
`

func (q *Queries) GetLast20ExportsByUserId(ctx context.Context, userID uuid.UUID) ([]Export, error) {
	rows, err := q.db.QueryContext(ctx, getLast20ExportsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Export
	for rows.Next() {
		var i Export
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ExportStatus,
			&i.StatusMessage,
			&i.UserID,
			&i.DownloadUrl,
			&i.ExportMethod,
			&i.TargetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
