// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logs.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createLog = `-- name: CreateLog :one
INSERT INTO
    logs (
        id,
        created_at,
        source_id,
        target_id,
        message
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, created_at, source_id, target_id, message
`

type CreateLogParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	SourceID  uuid.NullUUID
	TargetID  uuid.NullUUID
	Message   string
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, createLog,
		arg.ID,
		arg.CreatedAt,
		arg.SourceID,
		arg.TargetID,
		arg.Message,
	)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SourceID,
		&i.TargetID,
		&i.Message,
	)
	return i, err
}

const getRecentLogs = `-- name: GetRecentLogs :many
SELECT
    l.id,
    l.created_at,
    l.message,
    s.network AS source_network,
    s.user_name AS source_username,
    t.target_type AS target_type
FROM
    logs l
    LEFT JOIN sources s ON l.source_id = s.id
    LEFT JOIN targets t ON l.target_id = t.id
WHERE
    s.user_id = $1
    OR t.user_id = $1
ORDER BY l.created_at DESC
LIMIT 20
`

type GetRecentLogsRow struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	Message        string
	SourceNetwork  sql.NullString
	SourceUsername sql.NullString
	TargetType     sql.NullString
}

func (q *Queries) GetRecentLogs(ctx context.Context, userID uuid.UUID) ([]GetRecentLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentLogs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentLogsRow
	for rows.Next() {
		var i GetRecentLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Message,
			&i.SourceNetwork,
			&i.SourceUsername,
			&i.TargetType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncErrorsCountLast30Days = `-- name: GetSyncErrorsCountLast30Days :one
SELECT COUNT(*)
FROM
    logs l
    LEFT JOIN sources s ON l.source_id = s.id
    LEFT JOIN targets t ON l.target_id = t.id
WHERE (
        s.user_id = $1
        OR t.user_id = $1
    )
    AND created_at > NOW() - INTERVAL '30 days'
`

func (q *Queries) GetSyncErrorsCountLast30Days(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSyncErrorsCountLast30Days, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
