// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mappings.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createMappingForColumn = `-- name: CreateMappingForColumn :one
INSERT INTO column_mappings (id, created_at, table_mapping_id, source_column_name, target_column_name, target_column_code)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, table_mapping_id, source_column_name, target_column_name, target_column_code
`

type CreateMappingForColumnParams struct {
	ID               uuid.UUID
	CreatedAt        time.Time
	TableMappingID   uuid.UUID
	SourceColumnName string
	TargetColumnName string
	TargetColumnCode sql.NullString
}

func (q *Queries) CreateMappingForColumn(ctx context.Context, arg CreateMappingForColumnParams) (ColumnMapping, error) {
	row := q.db.QueryRowContext(ctx, createMappingForColumn,
		arg.ID,
		arg.CreatedAt,
		arg.TableMappingID,
		arg.SourceColumnName,
		arg.TargetColumnName,
		arg.TargetColumnCode,
	)
	var i ColumnMapping
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.TableMappingID,
		&i.SourceColumnName,
		&i.TargetColumnName,
		&i.TargetColumnCode,
	)
	return i, err
}

const createMappingForTable = `-- name: CreateMappingForTable :one
INSERT INTO table_mappings (id, created_at, source_table_name, target_table_name, target_table_code, target_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, source_table_name, target_table_name, target_table_code, target_id
`

type CreateMappingForTableParams struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	SourceTableName string
	TargetTableName string
	TargetTableCode sql.NullString
	TargetID        uuid.UUID
}

func (q *Queries) CreateMappingForTable(ctx context.Context, arg CreateMappingForTableParams) (TableMapping, error) {
	row := q.db.QueryRowContext(ctx, createMappingForTable,
		arg.ID,
		arg.CreatedAt,
		arg.SourceTableName,
		arg.TargetTableName,
		arg.TargetTableCode,
		arg.TargetID,
	)
	var i TableMapping
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SourceTableName,
		&i.TargetTableName,
		&i.TargetTableCode,
		&i.TargetID,
	)
	return i, err
}

const getColumnMappingsByTable = `-- name: GetColumnMappingsByTable :many
SELECT id, created_at, table_mapping_id, source_column_name, target_column_name, target_column_code FROM column_mappings
where table_mapping_id = $1
`

func (q *Queries) GetColumnMappingsByTable(ctx context.Context, tableMappingID uuid.UUID) ([]ColumnMapping, error) {
	rows, err := q.db.QueryContext(ctx, getColumnMappingsByTable, tableMappingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ColumnMapping
	for rows.Next() {
		var i ColumnMapping
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.TableMappingID,
			&i.SourceColumnName,
			&i.TargetColumnName,
			&i.TargetColumnCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getColumnMappingsByTableAndName = `-- name: GetColumnMappingsByTableAndName :one
SELECT cm.id, cm.created_at, cm.table_mapping_id, cm.source_column_name, cm.target_column_name, cm.target_column_code FROM column_mappings cm
left join table_mappings tm on cm.table_mapping_id = tm.id
where cm.table_mapping_id = $1 and cm.target_column_name = $2
`

type GetColumnMappingsByTableAndNameParams struct {
	TableMappingID   uuid.UUID
	TargetColumnName string
}

func (q *Queries) GetColumnMappingsByTableAndName(ctx context.Context, arg GetColumnMappingsByTableAndNameParams) (ColumnMapping, error) {
	row := q.db.QueryRowContext(ctx, getColumnMappingsByTableAndName, arg.TableMappingID, arg.TargetColumnName)
	var i ColumnMapping
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.TableMappingID,
		&i.SourceColumnName,
		&i.TargetColumnName,
		&i.TargetColumnCode,
	)
	return i, err
}

const getTableMappingsByTargetAndCode = `-- name: GetTableMappingsByTargetAndCode :one
SELECT id, created_at, source_table_name, target_table_name, target_table_code, target_id FROM table_mappings
WHERE target_id = $1 AND target_table_code = $2
`

type GetTableMappingsByTargetAndCodeParams struct {
	TargetID        uuid.UUID
	TargetTableCode sql.NullString
}

func (q *Queries) GetTableMappingsByTargetAndCode(ctx context.Context, arg GetTableMappingsByTargetAndCodeParams) (TableMapping, error) {
	row := q.db.QueryRowContext(ctx, getTableMappingsByTargetAndCode, arg.TargetID, arg.TargetTableCode)
	var i TableMapping
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SourceTableName,
		&i.TargetTableName,
		&i.TargetTableCode,
		&i.TargetID,
	)
	return i, err
}

const getTableMappingsByTargetAndName = `-- name: GetTableMappingsByTargetAndName :one
SELECT id, created_at, source_table_name, target_table_name, target_table_code, target_id FROM table_mappings
where target_id = $1 and target_table_name = $2
`

type GetTableMappingsByTargetAndNameParams struct {
	TargetID        uuid.UUID
	TargetTableName string
}

func (q *Queries) GetTableMappingsByTargetAndName(ctx context.Context, arg GetTableMappingsByTargetAndNameParams) (TableMapping, error) {
	row := q.db.QueryRowContext(ctx, getTableMappingsByTargetAndName, arg.TargetID, arg.TargetTableName)
	var i TableMapping
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SourceTableName,
		&i.TargetTableName,
		&i.TargetTableCode,
		&i.TargetID,
	)
	return i, err
}
