// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AnalyticsPageStat struct {
	ID       uuid.UUID
	Date     time.Time
	UrlPath  string
	Views    int32
	SourceID uuid.UUID
}

type AnalyticsPageStatsOnTarget struct {
	ID             uuid.UUID
	SyncedAt       time.Time
	StatID         uuid.UUID
	TargetID       uuid.UUID
	TargetRecordID string
}

type AnalyticsSiteStat struct {
	ID                 uuid.UUID
	Date               time.Time
	Visitors           int32
	AvgSessionDuration float64
	SourceID           uuid.UUID
}

type AnalyticsSiteStatsOnTarget struct {
	ID             uuid.UUID
	SyncedAt       time.Time
	StatID         uuid.UUID
	TargetID       uuid.UUID
	TargetRecordID string
}

type ColumnMapping struct {
	ID               uuid.UUID
	CreatedAt        time.Time
	TableMappingID   uuid.UUID
	SourceColumnName string
	TargetColumnName string
	TargetColumnCode sql.NullString
}

type Export struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	CompletedAt   time.Time
	ExportStatus  string
	StatusMessage sql.NullString
	UserID        uuid.UUID
	DownloadUrl   sql.NullString
	ExportMethod  string
	TargetID      uuid.NullUUID
}

type Log struct {
	ID        uuid.UUID
	CreatedAt time.Time
	SourceID  uuid.NullUUID
	TargetID  uuid.NullUUID
	Message   string
}

type Post struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	LastSyncedAt      time.Time
	SourceID          uuid.UUID
	IsArchived        bool
	NetworkInternalID string
	PostType          string
	Author            string
	Content           sql.NullString
}

type PostsOnTarget struct {
	ID            uuid.UUID
	FirstSyncedAt time.Time
	PostID        uuid.UUID
	TargetID      uuid.UUID
	TargetPostID  string
}

type PostsReactionsHistory struct {
	ID       uuid.UUID
	SyncedAt time.Time
	PostID   uuid.UUID
	Likes    sql.NullInt32
	Reposts  sql.NullInt32
	Views    sql.NullInt32
}

type Source struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Network      string
	UserName     string
	UserID       uuid.UUID
	IsActive     bool
	SyncStatus   string
	StatusReason sql.NullString
	LastSynced   sql.NullTime
}

type SourcesOnTarget struct {
	ID             uuid.UUID
	SourceID       uuid.UUID
	TargetID       uuid.UUID
	TargetSourceID string
}

type TableMapping struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	SourceTableName string
	TargetTableName string
	TargetTableCode sql.NullString
	TargetID        uuid.UUID
}

type Target struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	TargetType    string
	UserID        uuid.UUID
	DbID          sql.NullString
	IsActive      bool
	SyncFrequency string
	SyncStatus    string
	StatusReason  sql.NullString
	LastSynced    sql.NullTime
	HostUrl       sql.NullString
}

type Token struct {
	ID                   uuid.UUID
	EncryptedAccessToken []byte
	Nonce                []byte
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ProfileID            sql.NullString
	SourceID             uuid.NullUUID
	TargetID             uuid.NullUUID
}

type User struct {
	ID               uuid.UUID
	Username         string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	SyncPeriod       string
	EnabledOnStartup bool
}
