// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Export struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	CompletedAt   time.Time
	ExportStatus  string
	StatusMessage sql.NullString
	UserID        uuid.UUID
	DownloadUrl   sql.NullString
	ExportMethod  string
}

type Post struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	LastSyncedAt      time.Time
	SourceID          uuid.UUID
	IsArchived        bool
	NetworkInternalID string
	PostType          string
	Author            string
	Content           sql.NullString
}

type PostsReactionsHistory struct {
	ID       uuid.UUID
	SyncedAt time.Time
	PostID   uuid.UUID
	Likes    sql.NullInt32
	Reposts  sql.NullInt32
	Views    sql.NullInt32
}

type Source struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Network      string
	UserName     string
	UserID       uuid.UUID
	IsActive     bool
	SyncStatus   string
	StatusReason sql.NullString
	LastSynced   sql.NullTime
}

type Target struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	TargetType    string
	UserID        uuid.UUID
	DbID          sql.NullString
	IsActive      bool
	SyncFrequency string
	SyncStatus    string
	StatusReason  sql.NullString
	LastSynced    sql.NullTime
}

type Token struct {
	ID                   uuid.UUID
	EncryptedAccessToken []byte
	Nonce                []byte
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ProfileID            sql.NullString
	SourceID             uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Username  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
