// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkCountOfPostsForUser = `-- name: CheckCountOfPostsForUser :one
SELECT COUNT(*) FROM posts p
join sources s on p.source_id = s.id
where s.user_id = $1
`

func (q *Queries) CheckCountOfPostsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCountOfPostsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, created_at, last_synced_at, source_id, is_archived, network_internal_id, content, post_type, author)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, created_at, last_synced_at, source_id, is_archived, network_internal_id, post_type, author, content
`

type CreatePostParams struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	LastSyncedAt      time.Time
	SourceID          uuid.UUID
	IsArchived        bool
	NetworkInternalID string
	Content           sql.NullString
	PostType          string
	Author            string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.LastSyncedAt,
		arg.SourceID,
		arg.IsArchived,
		arg.NetworkInternalID,
		arg.Content,
		arg.PostType,
		arg.Author,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LastSyncedAt,
		&i.SourceID,
		&i.IsArchived,
		&i.NetworkInternalID,
		&i.PostType,
		&i.Author,
		&i.Content,
	)
	return i, err
}

const getAllPostsWithTheLatestInfoForUser = `-- name: GetAllPostsWithTheLatestInfoForUser :many
SELECT
    p.id,
    p.created_at,
    p.source_id,
    p.is_archived,
    p.network_internal_id,
    p.content,
    p.post_type,
    p.author,
    s.network AS network,
    u.username AS current_user_name,
    s.user_name AS source_user_name,
    r.synced_at AS reactions_synced_at,
    r.likes,
    r.reposts,
    r.views
FROM posts p
left join sources s
    ON p.source_id = s.id
left join users u on s.user_id = u.id
LEFT JOIN posts_reactions_history r
    ON r.post_id = p.id
   AND r.synced_at = (
        SELECT MAX(prh.synced_at)
        FROM posts_reactions_history prh
        WHERE prh.post_id = p.id
   )
WHERE s.user_id = $1
`

type GetAllPostsWithTheLatestInfoForUserRow struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	SourceID          uuid.UUID
	IsArchived        bool
	NetworkInternalID string
	Content           sql.NullString
	PostType          string
	Author            string
	Network           sql.NullString
	CurrentUserName   sql.NullString
	SourceUserName    sql.NullString
	ReactionsSyncedAt sql.NullTime
	Likes             sql.NullInt32
	Reposts           sql.NullInt32
	Views             sql.NullInt32
}

func (q *Queries) GetAllPostsWithTheLatestInfoForUser(ctx context.Context, userID uuid.UUID) ([]GetAllPostsWithTheLatestInfoForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPostsWithTheLatestInfoForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPostsWithTheLatestInfoForUserRow
	for rows.Next() {
		var i GetAllPostsWithTheLatestInfoForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SourceID,
			&i.IsArchived,
			&i.NetworkInternalID,
			&i.Content,
			&i.PostType,
			&i.Author,
			&i.Network,
			&i.CurrentUserName,
			&i.SourceUserName,
			&i.ReactionsSyncedAt,
			&i.Likes,
			&i.Reposts,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostByNetworkAndId = `-- name: GetPostByNetworkAndId :one
SELECT posts.id, posts.created_at, posts.last_synced_at, posts.source_id, posts.is_archived, posts.network_internal_id, posts.post_type, posts.author, posts.content FROM posts
join sources on posts.source_id = sources.id
where network_internal_id = $1 and sources.network = $2
`

type GetPostByNetworkAndIdParams struct {
	NetworkInternalID string
	Network           string
}

func (q *Queries) GetPostByNetworkAndId(ctx context.Context, arg GetPostByNetworkAndIdParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByNetworkAndId, arg.NetworkInternalID, arg.Network)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LastSyncedAt,
		&i.SourceID,
		&i.IsArchived,
		&i.NetworkInternalID,
		&i.PostType,
		&i.Author,
		&i.Content,
	)
	return i, err
}
