// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts_mappings.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addPostToTarget = `-- name: AddPostToTarget :one
INSERT INTO posts_on_target (id, first_synced_at, post_id, target_id, target_post_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, first_synced_at, post_id, target_id, target_post_id
`

type AddPostToTargetParams struct {
	ID            uuid.UUID
	FirstSyncedAt time.Time
	PostID        uuid.UUID
	TargetID      uuid.UUID
	TargetPostID  string
}

func (q *Queries) AddPostToTarget(ctx context.Context, arg AddPostToTargetParams) (PostsOnTarget, error) {
	row := q.db.QueryRowContext(ctx, addPostToTarget,
		arg.ID,
		arg.FirstSyncedAt,
		arg.PostID,
		arg.TargetID,
		arg.TargetPostID,
	)
	var i PostsOnTarget
	err := row.Scan(
		&i.ID,
		&i.FirstSyncedAt,
		&i.PostID,
		&i.TargetID,
		&i.TargetPostID,
	)
	return i, err
}

const getPostsPreviouslySynced = `-- name: GetPostsPreviouslySynced :many
SELECT id, first_synced_at, post_id, target_id, target_post_id FROM posts_on_target
where target_id = $1
`

func (q *Queries) GetPostsPreviouslySynced(ctx context.Context, targetID uuid.UUID) ([]PostsOnTarget, error) {
	rows, err := q.db.QueryContext(ctx, getPostsPreviouslySynced, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostsOnTarget
	for rows.Next() {
		var i PostsOnTarget
		if err := rows.Scan(
			&i.ID,
			&i.FirstSyncedAt,
			&i.PostID,
			&i.TargetID,
			&i.TargetPostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
