// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reactions.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const syncReactions = `-- name: SyncReactions :one
INSERT INTO posts_reactions_history (id, synced_at, post_id, likes, reposts, views)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, synced_at, post_id, likes, reposts, views
`

type SyncReactionsParams struct {
	ID       uuid.UUID
	SyncedAt time.Time
	PostID   uuid.UUID
	Likes    sql.NullInt32
	Reposts  sql.NullInt32
	Views    sql.NullInt32
}

func (q *Queries) SyncReactions(ctx context.Context, arg SyncReactionsParams) (PostsReactionsHistory, error) {
	row := q.db.QueryRowContext(ctx, syncReactions,
		arg.ID,
		arg.SyncedAt,
		arg.PostID,
		arg.Likes,
		arg.Reposts,
		arg.Views,
	)
	var i PostsReactionsHistory
	err := row.Scan(
		&i.ID,
		&i.SyncedAt,
		&i.PostID,
		&i.Likes,
		&i.Reposts,
		&i.Views,
	)
	return i, err
}
