// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: redirects.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRedirect = `-- name: CreateRedirect :one
INSERT INTO
    redirects (
        id,
        source_id,
        from_path,
        to_path,
        created_at
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, source_id, from_path, to_path, created_at
`

type CreateRedirectParams struct {
	ID        uuid.UUID
	SourceID  uuid.UUID
	FromPath  string
	ToPath    string
	CreatedAt time.Time
}

func (q *Queries) CreateRedirect(ctx context.Context, arg CreateRedirectParams) (Redirect, error) {
	row := q.db.QueryRowContext(ctx, createRedirect,
		arg.ID,
		arg.SourceID,
		arg.FromPath,
		arg.ToPath,
		arg.CreatedAt,
	)
	var i Redirect
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.FromPath,
		&i.ToPath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRedirect = `-- name: DeleteRedirect :exec
DELETE FROM redirects WHERE id = $1
`

func (q *Queries) DeleteRedirect(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRedirect, id)
	return err
}

const getRedirectById = `-- name: GetRedirectById :one
SELECT id, source_id, from_path, to_path, created_at FROM redirects WHERE id = $1
`

func (q *Queries) GetRedirectById(ctx context.Context, id uuid.UUID) (Redirect, error) {
	row := q.db.QueryRowContext(ctx, getRedirectById, id)
	var i Redirect
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.FromPath,
		&i.ToPath,
		&i.CreatedAt,
	)
	return i, err
}

const getRedirectForPath = `-- name: GetRedirectForPath :one
SELECT id, source_id, from_path, to_path, created_at FROM redirects WHERE source_id = $1 AND from_path = $2
`

type GetRedirectForPathParams struct {
	SourceID uuid.UUID
	FromPath string
}

func (q *Queries) GetRedirectForPath(ctx context.Context, arg GetRedirectForPathParams) (Redirect, error) {
	row := q.db.QueryRowContext(ctx, getRedirectForPath, arg.SourceID, arg.FromPath)
	var i Redirect
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.FromPath,
		&i.ToPath,
		&i.CreatedAt,
	)
	return i, err
}

const getRedirectsForSource = `-- name: GetRedirectsForSource :many
SELECT id, source_id, from_path, to_path, created_at
FROM redirects
WHERE
    source_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetRedirectsForSource(ctx context.Context, sourceID uuid.UUID) ([]Redirect, error) {
	rows, err := q.db.QueryContext(ctx, getRedirectsForSource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Redirect
	for rows.Next() {
		var i Redirect
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.FromPath,
			&i.ToPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
