// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSource = `-- name: CreateSource :one
INSERT INTO sources (id, created_at, updated_at, network, user_name, user_id, is_active)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, created_at, updated_at, network, user_name, user_id, is_active
`

type CreateSourceParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Network   string
	UserName  string
	UserID    uuid.UUID
	IsActive  bool
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, createSource,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Network,
		arg.UserName,
		arg.UserID,
		arg.IsActive,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Network,
		&i.UserName,
		&i.UserID,
		&i.IsActive,
	)
	return i, err
}

const getUserActiveSourceByName = `-- name: GetUserActiveSourceByName :one
SELECT id, created_at, updated_at, network, user_name, user_id, is_active FROM sources
where user_id = $1 and network = $2 and is_active = TRUE
LIMIT 1
`

type GetUserActiveSourceByNameParams struct {
	UserID  uuid.UUID
	Network string
}

func (q *Queries) GetUserActiveSourceByName(ctx context.Context, arg GetUserActiveSourceByNameParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, getUserActiveSourceByName, arg.UserID, arg.Network)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Network,
		&i.UserName,
		&i.UserID,
		&i.IsActive,
	)
	return i, err
}

const getUserActiveSources = `-- name: GetUserActiveSources :many
SELECT id, created_at, updated_at, network, user_name, user_id, is_active FROM sources
where user_id = $1 and is_active = TRUE
`

func (q *Queries) GetUserActiveSources(ctx context.Context, userID uuid.UUID) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, getUserActiveSources, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Network,
			&i.UserName,
			&i.UserID,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
