// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources_mappings.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addSourceToTarget = `-- name: AddSourceToTarget :one
INSERT INTO sources_on_target (id, source_id, target_id, target_source_id)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, source_id, target_id, target_source_id
`

type AddSourceToTargetParams struct {
	ID             uuid.UUID
	SourceID       uuid.UUID
	TargetID       uuid.UUID
	TargetSourceID string
}

func (q *Queries) AddSourceToTarget(ctx context.Context, arg AddSourceToTargetParams) (SourcesOnTarget, error) {
	row := q.db.QueryRowContext(ctx, addSourceToTarget,
		arg.ID,
		arg.SourceID,
		arg.TargetID,
		arg.TargetSourceID,
	)
	var i SourcesOnTarget
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.TargetSourceID,
	)
	return i, err
}

const getTargetSources = `-- name: GetTargetSources :many
SELECT id, source_id, target_id, target_source_id FROM sources_on_target
where target_id = $1
`

func (q *Queries) GetTargetSources(ctx context.Context, targetID uuid.UUID) ([]SourcesOnTarget, error) {
	rows, err := q.db.QueryContext(ctx, getTargetSources, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourcesOnTarget
	for rows.Next() {
		var i SourcesOnTarget
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.TargetSourceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTargetSourceById = `-- name: RemoveTargetSourceById :exec
DELETE FROM sources_on_target
where id = $1
`

func (q *Queries) RemoveTargetSourceById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeTargetSourceById, id)
	return err
}
