// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources_stats.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSourceStat = `-- name: CreateSourceStat :one
INSERT INTO
    sources_stats (
        id,
        date,
        source_id,
        followers_count,
        following_count,
        posts_count,
        average_likes,
        average_reposts,
        average_views
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9
    )
RETURNING
    id, date, source_id, followers_count, following_count, posts_count, average_likes, average_reposts, average_views
`

type CreateSourceStatParams struct {
	ID             uuid.UUID
	Date           time.Time
	SourceID       uuid.UUID
	FollowersCount sql.NullInt64
	FollowingCount sql.NullInt64
	PostsCount     sql.NullInt64
	AverageLikes   sql.NullFloat64
	AverageReposts sql.NullFloat64
	AverageViews   sql.NullFloat64
}

func (q *Queries) CreateSourceStat(ctx context.Context, arg CreateSourceStatParams) (SourcesStat, error) {
	row := q.db.QueryRowContext(ctx, createSourceStat,
		arg.ID,
		arg.Date,
		arg.SourceID,
		arg.FollowersCount,
		arg.FollowingCount,
		arg.PostsCount,
		arg.AverageLikes,
		arg.AverageReposts,
		arg.AverageViews,
	)
	var i SourcesStat
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.SourceID,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.PostsCount,
		&i.AverageLikes,
		&i.AverageReposts,
		&i.AverageViews,
	)
	return i, err
}

const getSourceStatsByDate = `-- name: GetSourceStatsByDate :one
SELECT id, date, source_id, followers_count, following_count, posts_count, average_likes, average_reposts, average_views
FROM sources_stats
WHERE
    source_id = $1
    AND date = $2
LIMIT 1
`

type GetSourceStatsByDateParams struct {
	SourceID uuid.UUID
	Date     time.Time
}

func (q *Queries) GetSourceStatsByDate(ctx context.Context, arg GetSourceStatsByDateParams) (SourcesStat, error) {
	row := q.db.QueryRowContext(ctx, getSourceStatsByDate, arg.SourceID, arg.Date)
	var i SourcesStat
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.SourceID,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.PostsCount,
		&i.AverageLikes,
		&i.AverageReposts,
		&i.AverageViews,
	)
	return i, err
}

const getSourceTotals = `-- name: GetSourceTotals :one
SELECT
    COUNT(DISTINCT p.id)::BIGINT AS total_posts,
    COALESCE(SUM(prh.likes), 0)::BIGINT AS total_likes,
    COALESCE(SUM(prh.reposts), 0)::BIGINT AS total_reposts,
    COALESCE(SUM(prh.views), 0)::BIGINT AS total_views
FROM posts p
    LEFT JOIN (
        SELECT DISTINCT
            ON (post_id) post_id, likes, reposts, views
        FROM posts_reactions_history
        ORDER BY post_id, synced_at DESC
    ) prh ON p.id = prh.post_id
WHERE
    p.source_id = $1
`

type GetSourceTotalsRow struct {
	TotalPosts   int
	TotalLikes   int
	TotalReposts int
	TotalViews   int
}

func (q *Queries) GetSourceTotals(ctx context.Context, sourceID uuid.UUID) (GetSourceTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, getSourceTotals, sourceID)
	var i GetSourceTotalsRow
	err := row.Scan(
		&i.TotalPosts,
		&i.TotalLikes,
		&i.TotalReposts,
		&i.TotalViews,
	)
	return i, err
}

const updateSourceDayStats = `-- name: UpdateSourceDayStats :one
UPDATE sources_stats
SET
    followers_count = $1,
    following_count = $2,
    posts_count = $3,
    average_likes = $4,
    average_reposts = $5,
    average_views = $6
WHERE
    source_id = $7
    AND date = $8
RETURNING
    id, date, source_id, followers_count, following_count, posts_count, average_likes, average_reposts, average_views
`

type UpdateSourceDayStatsParams struct {
	FollowersCount sql.NullInt64
	FollowingCount sql.NullInt64
	PostsCount     sql.NullInt64
	AverageLikes   sql.NullFloat64
	AverageReposts sql.NullFloat64
	AverageViews   sql.NullFloat64
	SourceID       uuid.UUID
	Date           time.Time
}

func (q *Queries) UpdateSourceDayStats(ctx context.Context, arg UpdateSourceDayStatsParams) (SourcesStat, error) {
	row := q.db.QueryRowContext(ctx, updateSourceDayStats,
		arg.FollowersCount,
		arg.FollowingCount,
		arg.PostsCount,
		arg.AverageLikes,
		arg.AverageReposts,
		arg.AverageViews,
		arg.SourceID,
		arg.Date,
	)
	var i SourcesStat
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.SourceID,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.PostsCount,
		&i.AverageLikes,
		&i.AverageReposts,
		&i.AverageViews,
	)
	return i, err
}
