// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const changeSourceStatusById = `-- name: ChangeSourceStatusById :one
UPDATE sources
SET is_active = $2, sync_status = $3, status_reason = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, network, user_name, user_id, is_active, sync_status, status_reason, last_synced
`

type ChangeSourceStatusByIdParams struct {
	ID           uuid.UUID
	IsActive     bool
	SyncStatus   string
	StatusReason sql.NullString
}

func (q *Queries) ChangeSourceStatusById(ctx context.Context, arg ChangeSourceStatusByIdParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, changeSourceStatusById,
		arg.ID,
		arg.IsActive,
		arg.SyncStatus,
		arg.StatusReason,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Network,
		&i.UserName,
		&i.UserID,
		&i.IsActive,
		&i.SyncStatus,
		&i.StatusReason,
		&i.LastSynced,
	)
	return i, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO sources (id, created_at, updated_at, network, user_name, user_id, is_active, sync_status, status_reason, last_synced)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, created_at, updated_at, network, user_name, user_id, is_active, sync_status, status_reason, last_synced
`

type CreateSourceParams struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Network      string
	UserName     string
	UserID       uuid.UUID
	IsActive     bool
	SyncStatus   string
	StatusReason sql.NullString
	LastSynced   sql.NullTime
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, createSource,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Network,
		arg.UserName,
		arg.UserID,
		arg.IsActive,
		arg.SyncStatus,
		arg.StatusReason,
		arg.LastSynced,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Network,
		&i.UserName,
		&i.UserID,
		&i.IsActive,
		&i.SyncStatus,
		&i.StatusReason,
		&i.LastSynced,
	)
	return i, err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources
WHERE id = $1
`

func (q *Queries) DeleteSource(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSource, id)
	return err
}

const getSourceById = `-- name: GetSourceById :one
SELECT id, created_at, updated_at, network, user_name, user_id, is_active, sync_status, status_reason, last_synced FROM sources
where id = $1
`

func (q *Queries) GetSourceById(ctx context.Context, id uuid.UUID) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSourceById, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Network,
		&i.UserName,
		&i.UserID,
		&i.IsActive,
		&i.SyncStatus,
		&i.StatusReason,
		&i.LastSynced,
	)
	return i, err
}

const getUserActiveSourceByName = `-- name: GetUserActiveSourceByName :one
SELECT id, created_at, updated_at, network, user_name, user_id, is_active, sync_status, status_reason, last_synced FROM sources
where user_id = $1 and network = $2 and is_active = TRUE
LIMIT 1
`

type GetUserActiveSourceByNameParams struct {
	UserID  uuid.UUID
	Network string
}

func (q *Queries) GetUserActiveSourceByName(ctx context.Context, arg GetUserActiveSourceByNameParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, getUserActiveSourceByName, arg.UserID, arg.Network)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Network,
		&i.UserName,
		&i.UserID,
		&i.IsActive,
		&i.SyncStatus,
		&i.StatusReason,
		&i.LastSynced,
	)
	return i, err
}

const getUserActiveSources = `-- name: GetUserActiveSources :many
SELECT id, created_at, updated_at, network, user_name, user_id, is_active, sync_status, status_reason, last_synced FROM sources
where user_id = $1 and is_active = TRUE
`

func (q *Queries) GetUserActiveSources(ctx context.Context, userID uuid.UUID) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, getUserActiveSources, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Network,
			&i.UserName,
			&i.UserID,
			&i.IsActive,
			&i.SyncStatus,
			&i.StatusReason,
			&i.LastSynced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSources = `-- name: GetUserSources :many
SELECT id, created_at, updated_at, network, user_name, user_id, is_active, sync_status, status_reason, last_synced FROM sources
where user_id = $1
ORDER BY
  CASE sync_status
    WHEN 'Initialized' THEN 1
    WHEN 'Deactivated' THEN 2
    WHEN 'Syncing' THEN 3
    ELSE 4
  END,
  last_synced DESC
`

func (q *Queries) GetUserSources(ctx context.Context, userID uuid.UUID) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, getUserSources, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Network,
			&i.UserName,
			&i.UserID,
			&i.IsActive,
			&i.SyncStatus,
			&i.StatusReason,
			&i.LastSynced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSourceSyncStatusById = `-- name: UpdateSourceSyncStatusById :one
UPDATE sources
SET sync_status = $2, status_reason = $3, last_synced = $4
WHERE id = $1
RETURNING id, created_at, updated_at, network, user_name, user_id, is_active, sync_status, status_reason, last_synced
`

type UpdateSourceSyncStatusByIdParams struct {
	ID           uuid.UUID
	SyncStatus   string
	StatusReason sql.NullString
	LastSynced   sql.NullTime
}

func (q *Queries) UpdateSourceSyncStatusById(ctx context.Context, arg UpdateSourceSyncStatusByIdParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, updateSourceSyncStatusById,
		arg.ID,
		arg.SyncStatus,
		arg.StatusReason,
		arg.LastSynced,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Network,
		&i.UserName,
		&i.UserID,
		&i.IsActive,
		&i.SyncStatus,
		&i.StatusReason,
		&i.LastSynced,
	)
	return i, err
}
