// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources_stats_noco.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addSourcesStatToTarget = `-- name: AddSourcesStatToTarget :one
INSERT INTO sources_stats_on_target (
    id,
    synced_at,
    stat_id,
    target_id,
    target_record_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, synced_at, stat_id, target_id, target_record_id
`

type AddSourcesStatToTargetParams struct {
	ID             uuid.UUID
	SyncedAt       time.Time
	StatID         uuid.UUID
	TargetID       uuid.UUID
	TargetRecordID string
}

func (q *Queries) AddSourcesStatToTarget(ctx context.Context, arg AddSourcesStatToTargetParams) (SourcesStatsOnTarget, error) {
	row := q.db.QueryRowContext(ctx, addSourcesStatToTarget,
		arg.ID,
		arg.SyncedAt,
		arg.StatID,
		arg.TargetID,
		arg.TargetRecordID,
	)
	var i SourcesStatsOnTarget
	err := row.Scan(
		&i.ID,
		&i.SyncedAt,
		&i.StatID,
		&i.TargetID,
		&i.TargetRecordID,
	)
	return i, err
}

const getAllSourcesStatsForUser = `-- name: GetAllSourcesStatsForUser :many
SELECT ss.id, ss.date, ss.source_id, ss.followers_count, ss.following_count, ss.posts_count, ss.average_likes, ss.average_reposts, ss.average_views
FROM sources_stats ss
    LEFT JOIN sources s ON ss.source_id = s.id
WHERE
    s.user_id = $1
ORDER BY ss.date DESC
`

func (q *Queries) GetAllSourcesStatsForUser(ctx context.Context, userID uuid.UUID) ([]SourcesStat, error) {
	rows, err := q.db.QueryContext(ctx, getAllSourcesStatsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourcesStat
	for rows.Next() {
		var i SourcesStat
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.SourceID,
			&i.FollowersCount,
			&i.FollowingCount,
			&i.PostsCount,
			&i.AverageLikes,
			&i.AverageReposts,
			&i.AverageViews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnsyncedSourcesStatsForTarget = `-- name: GetUnsyncedSourcesStatsForTarget :many
SELECT ss.id, ss.date, ss.source_id, ss.followers_count, ss.following_count, ss.posts_count, ss.average_likes, ss.average_reposts, ss.average_views
FROM sources_stats ss
WHERE ss.source_id = $1
AND NOT EXISTS (
    SELECT 1 FROM sources_stats_on_target ssot
    WHERE ssot.stat_id = ss.id
    AND ssot.target_id = $2
)
`

type GetUnsyncedSourcesStatsForTargetParams struct {
	SourceID uuid.UUID
	TargetID uuid.UUID
}

func (q *Queries) GetUnsyncedSourcesStatsForTarget(ctx context.Context, arg GetUnsyncedSourcesStatsForTargetParams) ([]SourcesStat, error) {
	rows, err := q.db.QueryContext(ctx, getUnsyncedSourcesStatsForTarget, arg.SourceID, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourcesStat
	for rows.Next() {
		var i SourcesStat
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.SourceID,
			&i.FollowersCount,
			&i.FollowingCount,
			&i.PostsCount,
			&i.AverageLikes,
			&i.AverageReposts,
			&i.AverageViews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
