// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserActiveSourceByName = `-- name: GetUserActiveSourceByName :one
SELECT id, created_at, updated_at, network, user_name, user_id, is_active, hashed_token FROM sources
where user_id = $1 and network = $2 and is_active = TRUE
LIMIT 1
`

type GetUserActiveSourceByNameParams struct {
	UserID  uuid.UUID
	Network string
}

func (q *Queries) GetUserActiveSourceByName(ctx context.Context, arg GetUserActiveSourceByNameParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, getUserActiveSourceByName, arg.UserID, arg.Network)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Network,
		&i.UserName,
		&i.UserID,
		&i.IsActive,
		&i.HashedToken,
	)
	return i, err
}
