// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: targets.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const changeTargetStatusById = `-- name: ChangeTargetStatusById :one
UPDATE targets
SET is_active = $2, sync_status = $3, status_reason = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, target_type, user_id, db_id, is_active, sync_frequency, sync_status, status_reason, last_synced, host_url
`

type ChangeTargetStatusByIdParams struct {
	ID           uuid.UUID      `json:"id"`
	IsActive     bool           `json:"is_active"`
	SyncStatus   string         `json:"sync_status"`
	StatusReason sql.NullString `json:"status_reason"`
}

func (q *Queries) ChangeTargetStatusById(ctx context.Context, arg ChangeTargetStatusByIdParams) (Target, error) {
	row := q.db.QueryRowContext(ctx, changeTargetStatusById,
		arg.ID,
		arg.IsActive,
		arg.SyncStatus,
		arg.StatusReason,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TargetType,
		&i.UserID,
		&i.DbID,
		&i.IsActive,
		&i.SyncFrequency,
		&i.SyncStatus,
		&i.StatusReason,
		&i.LastSynced,
		&i.HostUrl,
	)
	return i, err
}

const createTarget = `-- name: CreateTarget :one
INSERT INTO targets (id, created_at, updated_at, target_type, user_id, db_id, is_active, sync_frequency, sync_status, host_url)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, created_at, updated_at, target_type, user_id, db_id, is_active, sync_frequency, sync_status, status_reason, last_synced, host_url
`

type CreateTargetParams struct {
	ID            uuid.UUID      `json:"id"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	TargetType    string         `json:"target_type"`
	UserID        uuid.UUID      `json:"user_id"`
	DbID          sql.NullString `json:"db_id"`
	IsActive      bool           `json:"is_active"`
	SyncFrequency string         `json:"sync_frequency"`
	SyncStatus    string         `json:"sync_status"`
	HostUrl       sql.NullString `json:"host_url"`
}

func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) (Target, error) {
	row := q.db.QueryRowContext(ctx, createTarget,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.TargetType,
		arg.UserID,
		arg.DbID,
		arg.IsActive,
		arg.SyncFrequency,
		arg.SyncStatus,
		arg.HostUrl,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TargetType,
		&i.UserID,
		&i.DbID,
		&i.IsActive,
		&i.SyncFrequency,
		&i.SyncStatus,
		&i.StatusReason,
		&i.LastSynced,
		&i.HostUrl,
	)
	return i, err
}

const deleteTarget = `-- name: DeleteTarget :exec
DELETE FROM targets
WHERE id = $1
`

func (q *Queries) DeleteTarget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTarget, id)
	return err
}

const getTargetById = `-- name: GetTargetById :one
SELECT id, created_at, updated_at, target_type, user_id, db_id, is_active, sync_frequency, sync_status, status_reason, last_synced, host_url FROM targets
where id = $1
`

func (q *Queries) GetTargetById(ctx context.Context, id uuid.UUID) (Target, error) {
	row := q.db.QueryRowContext(ctx, getTargetById, id)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TargetType,
		&i.UserID,
		&i.DbID,
		&i.IsActive,
		&i.SyncFrequency,
		&i.SyncStatus,
		&i.StatusReason,
		&i.LastSynced,
		&i.HostUrl,
	)
	return i, err
}

const getUserActiveTargets = `-- name: GetUserActiveTargets :many
SELECT id, created_at, updated_at, target_type, user_id, db_id, is_active, sync_frequency, sync_status, status_reason, last_synced, host_url FROM targets
where is_active = TRUE and user_id = $1
`

func (q *Queries) GetUserActiveTargets(ctx context.Context, userID uuid.UUID) ([]Target, error) {
	rows, err := q.db.QueryContext(ctx, getUserActiveTargets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TargetType,
			&i.UserID,
			&i.DbID,
			&i.IsActive,
			&i.SyncFrequency,
			&i.SyncStatus,
			&i.StatusReason,
			&i.LastSynced,
			&i.HostUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTargets = `-- name: GetUserTargets :many
SELECT id, created_at, updated_at, target_type, user_id, db_id, is_active, sync_frequency, sync_status, status_reason, last_synced, host_url FROM targets
where user_id = $1
ORDER BY
  CASE sync_status
    WHEN 'Initialized' THEN 1
    WHEN 'Deactivated' THEN 2
    WHEN 'Syncing' THEN 3
    ELSE 4
  END,
  last_synced DESC
`

func (q *Queries) GetUserTargets(ctx context.Context, userID uuid.UUID) ([]Target, error) {
	rows, err := q.db.QueryContext(ctx, getUserTargets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TargetType,
			&i.UserID,
			&i.DbID,
			&i.IsActive,
			&i.SyncFrequency,
			&i.SyncStatus,
			&i.StatusReason,
			&i.LastSynced,
			&i.HostUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTargetSyncStatusById = `-- name: UpdateTargetSyncStatusById :one
UPDATE targets
SET sync_status = $2, status_reason = $3, last_synced = $4
WHERE id = $1
RETURNING id, created_at, updated_at, target_type, user_id, db_id, is_active, sync_frequency, sync_status, status_reason, last_synced, host_url
`

type UpdateTargetSyncStatusByIdParams struct {
	ID           uuid.UUID      `json:"id"`
	SyncStatus   string         `json:"sync_status"`
	StatusReason sql.NullString `json:"status_reason"`
	LastSynced   sql.NullTime   `json:"last_synced"`
}

func (q *Queries) UpdateTargetSyncStatusById(ctx context.Context, arg UpdateTargetSyncStatusByIdParams) (Target, error) {
	row := q.db.QueryRowContext(ctx, updateTargetSyncStatusById,
		arg.ID,
		arg.SyncStatus,
		arg.StatusReason,
		arg.LastSynced,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TargetType,
		&i.UserID,
		&i.DbID,
		&i.IsActive,
		&i.SyncFrequency,
		&i.SyncStatus,
		&i.StatusReason,
		&i.LastSynced,
		&i.HostUrl,
	)
	return i, err
}
