// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: targets.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTarget = `-- name: CreateTarget :one
INSERT INTO targets (id, created_at, updated_at, target_type, user_id, db_id, is_active, sync_frequency, sync_status)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, created_at, updated_at, target_type, user_id, db_id, is_active, sync_frequency, sync_status, status_reason, last_synced
`

type CreateTargetParams struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	TargetType    string
	UserID        uuid.UUID
	DbID          sql.NullString
	IsActive      bool
	SyncFrequency string
	SyncStatus    string
}

func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) (Target, error) {
	row := q.db.QueryRowContext(ctx, createTarget,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.TargetType,
		arg.UserID,
		arg.DbID,
		arg.IsActive,
		arg.SyncFrequency,
		arg.SyncStatus,
	)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TargetType,
		&i.UserID,
		&i.DbID,
		&i.IsActive,
		&i.SyncFrequency,
		&i.SyncStatus,
		&i.StatusReason,
		&i.LastSynced,
	)
	return i, err
}

const getAllActiveTargets = `-- name: GetAllActiveTargets :many
SELECT id, created_at, updated_at, target_type, user_id, db_id, is_active, sync_frequency, sync_status, status_reason, last_synced FROM targets
where is_active = TRUE
`

func (q *Queries) GetAllActiveTargets(ctx context.Context) ([]Target, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TargetType,
			&i.UserID,
			&i.DbID,
			&i.IsActive,
			&i.SyncFrequency,
			&i.SyncStatus,
			&i.StatusReason,
			&i.LastSynced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTargets = `-- name: GetAllTargets :many
SELECT id, created_at, updated_at, target_type, user_id, db_id, is_active, sync_frequency, sync_status, status_reason, last_synced FROM targets
`

func (q *Queries) GetAllTargets(ctx context.Context) ([]Target, error) {
	rows, err := q.db.QueryContext(ctx, getAllTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TargetType,
			&i.UserID,
			&i.DbID,
			&i.IsActive,
			&i.SyncFrequency,
			&i.SyncStatus,
			&i.StatusReason,
			&i.LastSynced,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
