// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (id, encrypted_access_token, nonce, created_at, updated_at, source_id, profile_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, encrypted_access_token, nonce, created_at, updated_at, profile_id, source_id
`

type CreateTokenParams struct {
	ID                   uuid.UUID
	EncryptedAccessToken []byte
	Nonce                []byte
	CreatedAt            time.Time
	UpdatedAt            time.Time
	SourceID             uuid.UUID
	ProfileID            sql.NullString
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.ID,
		arg.EncryptedAccessToken,
		arg.Nonce,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SourceID,
		arg.ProfileID,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.EncryptedAccessToken,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileID,
		&i.SourceID,
	)
	return i, err
}

const deleteTokenById = `-- name: DeleteTokenById :exec
DELETE FROM tokens
WHERE id = $1
`

func (q *Queries) DeleteTokenById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTokenById, id)
	return err
}

const getTokenBySource = `-- name: GetTokenBySource :one
SELECT id, encrypted_access_token, nonce, created_at, updated_at, profile_id, source_id FROM tokens
where source_id = $1
`

func (q *Queries) GetTokenBySource(ctx context.Context, sourceID uuid.UUID) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenBySource, sourceID)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.EncryptedAccessToken,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileID,
		&i.SourceID,
	)
	return i, err
}
