// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, created_at, updated_at, sync_method, access_key, target_database_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, username, created_at, updated_at, sync_method, access_key, target_database_id
`

type CreateUserParams struct {
	ID               uuid.UUID
	Username         string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	SyncMethod       string
	AccessKey        sql.NullString
	TargetDatabaseID sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SyncMethod,
		arg.AccessKey,
		arg.TargetDatabaseID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncMethod,
		&i.AccessKey,
		&i.TargetDatabaseID,
	)
	return i, err
}
