// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (
        id,
        username,
        created_at,
        updated_at,
        sync_period,
        enabled_on_startup
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, username, created_at, updated_at, sync_period, enabled_on_startup
`

type CreateUserParams struct {
	ID               uuid.UUID
	Username         string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	SyncPeriod       string
	EnabledOnStartup bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SyncPeriod,
		arg.EnabledOnStartup,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncPeriod,
		&i.EnabledOnStartup,
	)
	return i, err
}

const emptyUsers = `-- name: EmptyUsers :exec
DELETE FROM users
`

func (q *Queries) EmptyUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, emptyUsers)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, created_at, updated_at, sync_period, enabled_on_startup FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncPeriod,
			&i.EnabledOnStartup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserSyncSettings = `-- name: UpdateUserSyncSettings :one
UPDATE users
SET
    sync_period = $2,
    enabled_on_startup = $3,
    updated_at = NOW()
WHERE
    id = $1
RETURNING
    id, username, created_at, updated_at, sync_period, enabled_on_startup
`

type UpdateUserSyncSettingsParams struct {
	ID               uuid.UUID
	SyncPeriod       string
	EnabledOnStartup bool
}

func (q *Queries) UpdateUserSyncSettings(ctx context.Context, arg UpdateUserSyncSettingsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserSyncSettings, arg.ID, arg.SyncPeriod, arg.EnabledOnStartup)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncPeriod,
		&i.EnabledOnStartup,
	)
	return i, err
}
