// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (
        id,
        username,
        created_at,
        updated_at,
        sync_period,
        enabled_on_startup
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, username, created_at, updated_at, sync_period, enabled_on_startup, password_hash, totp_secret, totp_enabled
`

type CreateUserParams struct {
	ID               uuid.UUID
	Username         string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	SyncPeriod       string
	EnabledOnStartup bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SyncPeriod,
		arg.EnabledOnStartup,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncPeriod,
		&i.EnabledOnStartup,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
	)
	return i, err
}

const emptyUsers = `-- name: EmptyUsers :exec
DELETE FROM users
`

func (q *Queries) EmptyUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, emptyUsers)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, created_at, updated_at, sync_period, enabled_on_startup, password_hash, totp_secret, totp_enabled FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncPeriod,
			&i.EnabledOnStartup,
			&i.PasswordHash,
			&i.TotpSecret,
			&i.TotpEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, created_at, updated_at, sync_period, enabled_on_startup, password_hash, totp_secret, totp_enabled FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncPeriod,
		&i.EnabledOnStartup,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, created_at, updated_at, sync_period, enabled_on_startup, password_hash, totp_secret, totp_enabled FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncPeriod,
		&i.EnabledOnStartup,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET
    password_hash = $2,
    updated_at = NOW()
WHERE
    id = $1
RETURNING
    id, username, created_at, updated_at, sync_period, enabled_on_startup, password_hash, totp_secret, totp_enabled
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash sql.NullString
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncPeriod,
		&i.EnabledOnStartup,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
	)
	return i, err
}

const updateUserSyncSettings = `-- name: UpdateUserSyncSettings :one
UPDATE users
SET
    sync_period = $2,
    enabled_on_startup = $3,
    updated_at = NOW()
WHERE
    id = $1
RETURNING
    id, username, created_at, updated_at, sync_period, enabled_on_startup, password_hash, totp_secret, totp_enabled
`

type UpdateUserSyncSettingsParams struct {
	ID               uuid.UUID
	SyncPeriod       string
	EnabledOnStartup bool
}

func (q *Queries) UpdateUserSyncSettings(ctx context.Context, arg UpdateUserSyncSettingsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserSyncSettings, arg.ID, arg.SyncPeriod, arg.EnabledOnStartup)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncPeriod,
		&i.EnabledOnStartup,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
	)
	return i, err
}

const updateUserTOTP = `-- name: UpdateUserTOTP :one
UPDATE users
SET
    totp_secret = $2,
    totp_enabled = $3,
    updated_at = NOW()
WHERE
    id = $1
RETURNING
    id, username, created_at, updated_at, sync_period, enabled_on_startup, password_hash, totp_secret, totp_enabled
`

type UpdateUserTOTPParams struct {
	ID          uuid.UUID
	TotpSecret  sql.NullString
	TotpEnabled sql.NullBool
}

func (q *Queries) UpdateUserTOTP(ctx context.Context, arg UpdateUserTOTPParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserTOTP, arg.ID, arg.TotpSecret, arg.TotpEnabled)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncPeriod,
		&i.EnabledOnStartup,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.TotpEnabled,
	)
	return i, err
}
